// Generated by CoffeeScript 1.12.3
(function() {
  var AmqpSubscriberDriver, AsyncBinaryState, DeclarationManager, EventEmitter, JsonSerialization, bluebird,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  bluebird = require("bluebird");

  EventEmitter = require("events").EventEmitter;

  DeclarationManager = require("./DeclarationManager");

  JsonSerialization = require("../../serialization/JsonSerialization");

  AsyncBinaryState = require("../../AsyncBinaryState");

  module.exports = AmqpSubscriberDriver = (function(superClass) {
    extend(AmqpSubscriberDriver, superClass);

    function AmqpSubscriberDriver(channel, declarationManager, serialization) {
      this.channel = channel;
      this.declarationManager = declarationManager != null ? declarationManager : new DeclarationManager(this.channel);
      this.serialization = serialization != null ? serialization : new JsonSerialization();
      this._message = bind(this._message, this);
      this._count = 0;
      this._consumeState = new AsyncBinaryState();
      this._consumerTag = null;
    }

    AmqpSubscriberDriver.prototype.subscribe = function(topic) {
      topic = this._normalizeTopic(topic);
      ++this._count;
      return this._consume().then((function(_this) {
        return function() {
          return bluebird.join(_this.declarationManager.queue(), _this.declarationManager.exchange(), function(queue, exchange) {
            return _this.channel.bindQueue(queue, exchange, topic);
          });
        };
      })(this))["catch"]((function(_this) {
        return function(error) {
          --_this._count;
          throw error;
        };
      })(this));
    };

    AmqpSubscriberDriver.prototype.unsubscribe = function(topic) {
      topic = this._normalizeTopic(topic);
      --this._count;
      return bluebird.join(this.declarationManager.queue(), this.declarationManager.exchange(), (function(_this) {
        return function(queue, exchange) {
          return _this.channel.unbindQueue(queue, exchange, topic);
        };
      })(this))["catch"]((function(_this) {
        return function(error) {
          ++_this._count;
          throw error;
        };
      })(this)).then((function(_this) {
        return function() {
          if (!_this._count) {
            return _this._cancelConsume();
          }
        };
      })(this));
    };

    AmqpSubscriberDriver.prototype._normalizeTopic = function(topic) {
      return topic.replace(/\*/g, "#").replace(/\?/g, "*");
    };

    AmqpSubscriberDriver.prototype._consume = function() {
      return this._consumeState.setOn((function(_this) {
        return function() {
          var consumer;
          consumer = _this.declarationManager.queue().then(function(queue) {
            return _this.channel.consume(queue, _this._message, {
              noAck: true
            });
          });
          return consumer.then(function(response) {
            return _this._consumerTag = response.consumerTag;
          })["catch"](function(error) {
            _this._consumerTag = null;
            throw error;
          });
        };
      })(this));
    };

    AmqpSubscriberDriver.prototype._cancelConsume = function() {
      return this._consumeState.setOff((function(_this) {
        return function() {
          var cancel, consumerTag;
          consumerTag = _this._consumerTag;
          cancel = _this.channel.cancel(_this._consumerTag);
          return cancel.then(function() {
            return _this._consumerTag = null;
          })["catch"](function(error) {
            _this._consumerTag = consumerTag;
            throw error;
          });
        };
      })(this));
    };

    AmqpSubscriberDriver.prototype._message = function(message) {
      var payload, payloadString, topic;
      topic = message.fields.routingKey;
      payloadString = message.content.toString();
      payload = this.serialization.unserialize(payloadString);
      return this.emit("message", topic, payload);
    };

    return AmqpSubscriberDriver;

  })(EventEmitter);

}).call(this);

//# sourceMappingURL=AmqpSubscriberDriver.js.map
