// Generated by CoffeeScript 1.12.3
(function() {
  var ExecutionError, ResponseCode,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ResponseCode = require("../message/ResponseCode");

  module.exports = ExecutionError = (function(superClass) {
    extend(ExecutionError, superClass);

    function ExecutionError(message) {
      this.message = message;
      this.responseCode = ResponseCode.ERROR;
    }

    return ExecutionError;

  })(Error);

}).call(this);

//# sourceMappingURL=ExecutionError.js.map
