// Generated by CoffeeScript 1.12.3
(function() {
  var InvalidMessageError, ResponseCode,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ResponseCode = require("../message/ResponseCode");

  module.exports = InvalidMessageError = (function(superClass) {
    extend(InvalidMessageError, superClass);

    function InvalidMessageError(message) {
      this.message = message;
      this.responseCode = ResponseCode.INVALID_MESSAGE;
    }

    return InvalidMessageError;

  })(Error);

}).call(this);

//# sourceMappingURL=InvalidMessageError.js.map
