// Generated by CoffeeScript 1.12.3
(function() {
  var TimeoutError,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  module.exports = TimeoutError = (function(superClass) {
    extend(TimeoutError, superClass);

    function TimeoutError(timeout) {
      this.timeout = timeout;
      this.message = "RPC call timed out after " + this.timeout + " seconds.";
    }

    return TimeoutError;

  })(Error);

}).call(this);

//# sourceMappingURL=TimeoutError.js.map
