// Generated by CoffeeScript 1.12.3
(function() {
  var ResponseCode, UnknownProcedureError,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ResponseCode = require("../message/ResponseCode");

  module.exports = UnknownProcedureError = (function(superClass) {
    extend(UnknownProcedureError, superClass);

    function UnknownProcedureError(procedureName) {
      this.procedureName = procedureName;
      this.message = "Unknown procedure: " + this.procedureName + ".";
      this.responseCode = ResponseCode.UNKNOWN_PROCEDURE;
    }

    return UnknownProcedureError;

  })(Error);

}).call(this);

//# sourceMappingURL=UnknownProcedureError.js.map
