language: node_js

node_js:
    - '5'
    - '6'

script: make test

deploy:
    provider: npm
    email: james.harris@icecave.com.au
    api_key:
         secure: "1BZdwy93MPeagxO0e7mWX4mUWUN0wkX7D/1sBrZyp6ZTG3vnJf98HwQSdiUIFe1cYvID1PrWhdM+qhKNYfQN4rKbgPbbxJwV/Ue5UHM6GI4KVrovCIlPRCo3aYA9mVudGkXK4xHhG225tpmUYgIKlCkAj+pzpxMzzyOxvU/7Aa0="
    on:
        repo: IcecaveStudios/overpass-js
        tags: true
        node: '6'
