// Generated by CoffeeScript 1.12.3
(function() {
  var JsonSerialization;

  module.exports = JsonSerialization = (function() {
    function JsonSerialization() {}

    JsonSerialization.prototype.serialize = function(payload) {
      var ref;
      if (((ref = typeof payload) !== "object" && ref !== "array") || payload === null) {
        throw new Error("Payload must be an object or an array.");
      }
      return new Buffer(JSON.stringify(payload));
    };

    JsonSerialization.prototype.unserialize = function(buffer) {
      var payload, ref;
      try {
        payload = JSON.parse(buffer.toString());
      } catch (error) {
        throw new Error("Could not unserialize payload.");
      }
      if (((ref = typeof payload) !== "object" && ref !== "array") || payload === null) {
        throw new Error("Payload must be an object or an array.");
      }
      return payload;
    };

    return JsonSerialization;

  })();

}).call(this);

//# sourceMappingURL=JsonSerialization.js.map
