// Generated by CoffeeScript 1.12.3
(function() {
  var Enum;

  Enum = require("enum");

  module.exports = new Enum({
    SUCCESS: 0,
    ERROR: 10,
    INVALID_MESSAGE: 11,
    UNKNOWN_PROCEDURE: 12,
    INVALID_ARGUMENTS: 13
  });

}).call(this);

//# sourceMappingURL=ResponseCode.js.map
